import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import path from "node:path";
import fs from "node:fs";
import { exec } from "node:child_process";

let manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const vaultConfigDirs = [
	"test/vault/.obsidian",
];

const copyOutputPlugin = {
	name: "copy-output",
	setup(build) {
		build.onEnd(() => {
			for (const configDir of vaultConfigDirs) {
				const pluginDir = path.join(configDir, "plugins", manifest.id);
				if (!fs.existsSync(configDir)) {
					console.warn(
						`[copy-output] Skipping missing vault: ${configDir}`,
					);
					continue;
				}
				fs.mkdirSync(pluginDir, { recursive: true });
				for (const file of ["main.js", "manifest.json", "styles.css"]) {
					fs.copyFileSync(file, path.join(pluginDir, file));
				}
			}
		});
	},
};

const reloadObsidianPlugin = {
	name: "reload-obsidian-plugin",
	setup(build) {
		build.onEnd(() => {
			exec(
				`obsidian plugin:reload id=${manifest.id}`,
				{ cwd: path.join(process.cwd(), "test", "vault") },
				(error, stdout, stderr) => {
					if (error) {
						console.error(
							`[reload-obsidian-plugin] Error reloading plugin: ${error.message}`,
						);
						return;
					}
					if (stderr) {
						console.error(
							`[reload-obsidian-plugin] Error reloading plugin: ${stderr}`,
						);
						return;
					}
					console.log(
						`[reload-obsidian-plugin] Plugin reloaded: ${manifest.id}`,
					);
				},
			);
		});
	},
};

const prod = process.argv[2] === "production";

let entryPoint = "src/main.ts";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// "@codemirror/autocomplete", // Appears that Obsidian is monkey-patching this, need default functionality for closeBrackets
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	loader: {
		".svg": "text",
	},
	plugins: [copyOutputPlugin, reloadObsidianPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
